# Generated by Django 4.1.4 on 2022-12-22 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EpiTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de EPI',
                'verbose_name_plural': 'Tipos de EPI',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Epi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificacao', models.CharField(max_length=50, verbose_name='Especificação')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='epi.epitipo', verbose_name='Tipo de EPI')),
            ],
            options={
                'verbose_name': 'EPI',
                'verbose_name_plural': 'EPIs',
                'ordering': ['especificacao'],
            },
        ),
        migrations.CreateModel(
            name='CA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
                ('validade', models.DateField()),
                ('tipos', models.ManyToManyField(to='epi.epitipo')),
            ],
            options={
                'verbose_name': 'CA',
                'verbose_name_plural': 'CAs',
                'ordering': ['descricao', 'validade'],
            },
        ),
    ]
